name: Pytest

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout üõéÔ∏è
      uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: install gdal
      run: |
        sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
        sudo apt-get update
        sudo apt-get install libgdal-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # pin virtualenv pipenv b/c of problem with use_2to3 in setuptools 58.*
        # pip install --upgrade --no-cache-dir setuptools pip
        pip install --no-cache-dir virtualenv==v20.7.2 pipenv
        PIPENV_VENV_IN_PROJECT=1 pipenv --three
        pipenv sync --dev
    - name: Test with pytest
      run: |
        pipenv run pytest -vv
    - name: Run black
      run: |
        pipenv run black .
